[[sources]]
type = "crates_io"
crate = "crab-hole"
allow_yanked = false #default

[[sources]]
type = "github_release"
repo = "Robosturm/Commander_Wars"
allow_prerelease = false #default

[[sources]]
type = "github_tag"
repo = "ankitects/anki"

[[sources]]
type = "docker_hub"
namespace = "_"
image = "alpine"
tag = "latest" #default

[[sources]]
type = "manual"
version = "1.8.9"

